### ISSUE TITLE
Case when urls are differs from actual file sizes

### ISSUE THREAD

**Issue by dlobashevsky** [homebase/bigpack#1]
We have a lot of files placed on /mount/cache/parallel/0 , /mount/cache/parallel/1 ...
Also folder structure is $prefix/12-/124/35-/443/23.png for every stream.
But server should retrieve data from urls like https://$server/tiles/12/12435/44323.png
While BigPack is fast, renaming 10^8 files and join them to single folder take a lot of time.
Simple solution is prepare files list (as addFromFileList ) having two fields - actual file name and correspondent relative url.

**Comment by parf** [comment]
Done.

Check Advanced Usage (Data-Source-FileName) section.
So you can add entries like this to filelist.bigpack.gz:
passwd  600     1532024127      /etc/passwd
filename 600 1532024127 /u/disk1/filename

> bigpack help generateFileList

Generate File List from current directory for addFromFileList command

Filelist is gzip of `find . -printf "%p\t%m\t%T@\n" | sed 's/^\.\///'` command
e.g. tab delimited list of "FileName FileMod LastModifiedUnixTime"
Example: "somedir/README.md\t664\t1543616888" where "\t" is tab character

".*" files/directories ignored (hidden files). ex: ".git" directory ignored
"*.gz" files ignored

On terabyte+ filesystems generation process alone can take hours (even on SSD)

**Advanced Usage (Data-Source-FileName):
   you can specify Data-Source-FileName for a File (relative or absolute filename)
   tab delimited list of "FileName FileMod LastModifiedUnixTime DataSourceFileName"**


PS: 
 right now generateFileList is just a shell script:
    static function generateFileList() {
        $cmd = "find . -path \"./.*\" -prune -o -path \"*.gz\" -prune -o -path \"*/.*\" -prune -o -type f -printf \"%p\t%m\t%T@\n\"";
        echo shell_exec($cmd.' | sed \'s/^\.\///\' | sed \'s/\.[0-9]*$//\' | gzip > filelist.bigpack.gz');
    }
